CONSTRUCT 
{
  ?cc bk:_parentId ?parentId;
    dcterms:identifier ?id;
    rdfs:label ?label;
  	dcterms:description ?description.
}
WHERE
{
	VALUES ( ?cc ) {
	  $resourceIris
	} 

  ?cc dcterms:identifier ?id;
  		rdfs:subClassOf ?parent.
  		
  ?parent bk:isOndexPreferred true.
  ?parent dcterms:identifier ?parentIdRaw.  		
  
  BIND ( IF ( ?parentIdRaw = 'Concept', 'Thing', ?parentIdRaw ) AS ?parentId )
   
  OPTIONAL { ?cc rdfs:label ?label }
  OPTIONAL { ?cc dcterms:description ?description }
}
