language: java

jdk:
  - openjdk11

sudo: required

before_script:
  - sudo apt-get update
 # We need this due to: https://github.com/lukaszlenart/launch4j-maven-plugin/issues/29
  - sudo apt-get install libc6:i386 libstdc++6:i386
  - echo "export MAVEN_OPTS='-Xms1G -Xmx4G -Dsun.net.client.defaultConnectTimeout=600000 -Dsun.net.client.defaultReadTimeout=600000'" >~/.mavenrc
# Headless start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # Common settings defining Knetminer server passwords and the like.
  - wget https://raw.githubusercontent.com/Rothamsted/knetminer-common/master/settings.xml
    

install: echo "Skipping default installation step"

script:
  - mvn deploy --settings settings.xml

