language: java

jdk:
  - openjdk11

services:
  - xvfb # To manage Headless Java

before_script:
  - sudo apt-get update
# We need this due to: https://github.com/lukaszlenart/launch4j-maven-plugin/issues/29
  - sudo apt-get install libc6:i386 libstdc++6:i386
  - echo "export MAVEN_OPTS='-Xms1G -Xmx4G -Dsun.net.client.defaultConnectTimeout=600000 -Dsun.net.client.defaultReadTimeout=600000'" >~/.mavenrc
# We need to reduce Maven verbosity, Travis has an out limit
  - echo 'export MAVEN_OPTS="$MAVEN_OPTS -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO"' >>~/.mavenrc
# Headless Java
  - "export DISPLAY=:99.0"
  - wget --no-verbose https://raw.githubusercontent.com/Rothamsted/knetminer-common/master/settings.xml
    

install: echo "Skipping default installation step"

script:
  - >
      mvn deploy --no-transfer-progress --batch-mode --settings settings.xml |
      egrep --ignore-case --invert-match '(\[DEBUG\]|already added\, skipping|Copying|Adding)'

cache:
  directories:
    - $HOME/.m2
