ASK {
	bkr:to_0000233  bk:is_a     bkr:to_0000043 ;
					bk:ondexId 					?ondexId;
	        bk:prefName         "root volume" ;
	        bk:altName          "RTVOL" ;
	        rdf:type            bk:TO ;
	        dc:identifier       bkr:accsn_to_0000233 ;
	        bk:dataSource       bk:TO ;
	        rdfs:comment        "Is an indirect measure of root mass or density. Quantified in terms of cubic centimeters by water displacement method. ( Reference: GR:pj GR_REF:6917 )" ;
	        dcterms:identifier  "TO:0000233" ;
	        bk:evidence         bk:IMPD .
	
	FILTER ( ?ondexId > 0 )
          
	bkr:accsn_to_0000233  rdf:type  bk:Accession ;
	        bk:dataSource       bk:TO ;
	        dcterms:identifier  "TO:0000233" .        
}