ASK {
	bk:Protein  rdfs:subClassOf  bk:MolCmplx ;
	        dcterms:description  "A protein is comprised of one or more Polypeptides and potentially other molecules.\n\t\t\t\t" ;
	        rdfs:label           "Protein" ;
	        dcterms:identifier   "Protein" .
	        	        
	bk:Transporter  rdfs:subClassOf  bk:Protein ;
	        dcterms:description  "A protein that transports compounds through membranes between different cellular\n\t\t\t\t\tcompartments.\n\t\t\t\t" ;
	        rdfs:label           "Transporter" ;
	        dcterms:identifier   "Transporter" .
	        
	bk:MolCmplx  rdfs:subClassOf  bk:Participant ;
	        dcterms:description  "An entity comprised of one or more molecules\n\t\t\t\t\t" ;
	        rdfs:label           "Molecule Complex" ;
	        dcterms:identifier   "MolCmplx" .
}
