ASK {
	bk:IMPD  rdf:type            bk:EvidenceType ;
	        dcterms:description  "imported from database\n\t\t\t\t" ;
	        rdfs:label           "Imported from database" ;
	        dcterms:identifier   "IMPD" .

	bk:UNIPROTKB_SwissProt
	        rdf:type             bk:DataSource ;
	        dcterms:description  "UniProtKB/Swiss-Prot is a reviewed and manually-annotated\n\t\t\t\t\tprotein sequence database.\n\t\t\t\t\t- http://www.uniprot.org/\n\t\t\t\t" ;
	        rdfs:label           "UniProtKB/Swiss-Prot" ;
	        dcterms:identifier   "UNIPROTKB-SwissProt" .
}