# Extracts all the constraints of some-values-from or all-values-from, to be used to 
# establish new mappings to the Ondex OWL parser.
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bk: <http://www.ondex.org/bioknet/terms/>
PREFIX bkr: <http://www.ondex.org/bioknet/resources/>
PREFIX bka: <http://www.ondex.org/bioknet/attributes/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?kind ?onProp ?onProplabel ?onPropDef #?target ?targetlabel
{ 
   ?r a owl:Restriction;
    owl:onProperty ?onProp;
	?kind ?target.

  FILTER ( ?kind IN (owl:someValuesFrom, owl:allValuesFrom) )
  OPTIONAL { ?onProp rdfs:label ?onProplabel }
  OPTIONAL { ?onProp obo:IAO_0000115 ?onPropDef }
  OPTIONAL { ?target rdfs:label ?targetlabel }
}
LIMIT 1000
