PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bk: <http://knetminer.org/data/rdf/terms/biokno/>
PREFIX bkr: <http://knetminer.org/data/rdf/resources/>
PREFIX bka: <http://knetminer.org/data/rdf/terms/biokno/attributes/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?name ?value
{
	{ 
	  ?iri ?name ?value.

	  VALUES ( ?name ) {
	    (dcterms:identifier)
	    (dcterms:description)
	    (rdfs:comment)
	    (bk:prefName)
	    (bk:altName)
	    (bk:ondexId)
	  }
	}
	UNION {
	  ?iri ?name ?value.

	  # This is an attribute added by the RDF exporter, we already have it as 'iri' property, so let's avoid
	  # redundancies
	  FILTER ( ?name != bka:iri ) 
	  
		?name rdfs:subPropertyOf* bk:attribute.
	}
}
