package net.sourceforge.ondex.scripting.base;

public interface UniversalConstants {
	public static final String NEXT = ", ";
	public static final String SC = ";";
	public static final String EMPTY = "";
	public static final String PUBLIC_STATIC = "public static ";
	public static final String PRIVATE_STATIC = "private static ";
	public static final String PUBLIC = "public ";
	public static final String PROTECTED = "protected ";
	public static final String NO_BODY = "super();";
	public static final String SPACE = " ";
	public static final String BR_OPEN = "(";
	public static final String ARG = "arg";
	public static final String OWNER = "owner";
	public static final String M_START = "{\n\t";
	public static final String RETURN = "return ";
	public static final String DOT = ".";
	public static final String BR_LN_M_END = ");\n}";
	public static final String LN_END = ";\n\t";
	public static final String NL_TB = "\n\t";
	public static final String EQ = " = ";
	public static final String CLS = "}";
	public static final String CASHE = "cashe";
	public static final String BR_CLOSE = ")";
	public static final String FNEX ="throws net.sourceforge.ondex.scripting.FunctionException"; 
	public static final String TRY_OPN = "try {";
	public static final String TRY_CLS = "catch (java.lang.NullPointerException e){\n\t throw new net.sourceforge.ondex.scripting.FunctionException(";
	public static final String QT = "\"";
	public static final String ERRMSG = " is missing dependancies in the execution envieronment.\", -4";
	public static final String UNWRP_METHOD = "public java.lang.Object unwrap(){return baseObject;}";
	public static final String WRP_METHOD1 = "public void wrap(Object o){this.baseObject = (";
	public static final String WRP_METHOD2 = ")o;}";
	public static final String BS = " baseObject";
	public static final String MTH_NM1 = "public String getClassName() {return \"";
	public static final String MTH_NM2 = "\";}";
	public static final String UNWRP_ARG = ").unwrap()";
	public static final String WRP = "((net.sourceforge.ondex.scripting.base.ScriptingWrapper)";
	public static final String WRAPPER = "net.sourceforge.ondex.scripting.base.ScriptingWrapper";
	public static final String GLOBAL_FUNCTIONS = "net.sourceforge.ondex.scripted.Global";
	public static final String WRAPPER_PACKAGE = "net.sourceforge.ondex.scripted";
	public static final String APPBASE_MTHD ="public static void setBase(java.util.Map base){";
	public static final String MAP_GET_STR = "base.get(";
	public static final String MAP_GET_END = ".class);\n";
	public static final String SET_BASE = "setBase";
}
