# We don't need this as distinct, since URIs are pre-collected inot a Map 
SELECT ?resourceIri ?ondexId
WHERE {
  ?resourceIri rdf:type/rdfs:subClassOf* bk:Concept.
  
  # These are foo test cases in the ontology file.
  FILTER ( ?resourceIri NOT IN ( bk:testConcept0_1, bk:testConcept0_2 ) )
  
  # If not present, we auto-generate it.
  OPTIONAL { ?resourceIri bk:ondexId ?ondexId }
}
