# Deals with metadata elements like evidence, datasource, unit, which have all the same structure.
#
CONSTRUCT 
{
  ?meta
    dcterms:identifier ?id;
    rdfs:label ?label;
  	dcterms:description ?description;
}
WHERE
{
	VALUES ( ?meta ) {
	  $resourceIris
	} 

  ?meta dcterms:identifier ?id.
  
  OPTIONAL { ?meta rdfs:label ?label }
  OPTIONAL { ?meta dcterms:description ?description }
}
